[package]
edition = "2021"
name    = "got-ur-logs-uwu"
version = "0.1.0"

[dependencies]
gag          = "1.0.0"
handlebars   = "4.4.0"
lazy_static  = "1.4.0"
mockall      = "0.11.4"
rstest       = "0.18.2"
strum        = "0.25.0"
strum_macros = "0.25.2"
thiserror    = "1.0.48"
